-- ============================================================
-- Otomatik yedekleme (nokta-zaman kurtarma) — app_db_history.
--
-- Bu betiği bir kez Supabase Dashboard > SQL Editor içinde çalıştırın
-- (proje: frvjglboljauukgxqetp). Tekrar çalıştırmak güvenlidir
-- (idempotent) — zaten var olan nesneler atlanır.
--
-- Amaç: hatalı bir işlem, yanlış "Yedek Geri Yükle" ya da beklenmeyen bir
-- durum yüzünden merkezi veri (app_db) bozulursa/eksilirse, en fazla 30
-- dakika öncesine kadar geri dönebilecek bir kurtarma noktası zinciri
-- tutmak. Kullanıcı müdahalesi gerektirmez — her kaydetmede otomatik
-- çalışır; en fazla 30 dakikada bir yeni anlık görüntü alınır (sık
-- kaydetmelerde depolamayı şişirmemek için) ve 30 günden eski anlık
-- görüntüler otomatik silinir.
-- ============================================================

create table if not exists public.app_db_history (
  id bigint generated by default as identity primary key,
  data jsonb not null,
  updated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

alter table public.app_db_history enable row level security;

-- Herkes (giriş yapmış) geçmişi görebilir — geri yükleme kararını verebilmek
-- için gereklidir. İstemciden INSERT/UPDATE/DELETE yapılamaz (politika
-- tanımlanmadığından varsayılan olarak reddedilir) — satırlar yalnızca
-- aşağıdaki tetikleyiciyle, sunucu tarafında oluşur; böylece geçmiş kaydı
-- istemciden kurcalanamaz/silinemez.
drop policy if exists "authenticated select app_db_history" on public.app_db_history;
create policy "authenticated select app_db_history" on public.app_db_history
  for select to authenticated using (true);

create or replace function public.app_db_snapshot()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  if not exists (
    select 1 from public.app_db_history where created_at > now() - interval '30 minutes'
  ) then
    insert into public.app_db_history (data, updated_by) values (new.data, new.updated_by);
  end if;
  delete from public.app_db_history where created_at < now() - interval '30 days';
  return new;
end;
$$;

drop trigger if exists on_app_db_change on public.app_db;
create trigger on_app_db_change
  after insert or update on public.app_db
  for each row execute function public.app_db_snapshot();

-- Kurulum anında en az bir kurtarma noktası olsun diye mevcut veriyi hemen
-- bir kez anlık görüntüye al (yalnızca geçmiş tablosu boşsa — tekrar
-- çalıştırıldığında yinelenen kayıt oluşturmaz).
insert into public.app_db_history (data, updated_by)
select data, updated_by from public.app_db
where id = 1 and not exists (select 1 from public.app_db_history);
